### PR TITLE
Use ez_setup instead of distribute_setup

### PR DESCRIPTION
**Pull request by saschpe**
Distribute merged into setuptools a while ago. Thus use the latter
again.

### CODE REVIEW

**Comment by methane** [comment]
Current `setup.py` simply uses setuptools without `distribute_setup` or `ez_setup`.
I think this PR should be closed.

**Comment by saschpe** [comment]
What do you mean by _current_? The pull is still mergable so nothing changed in the master branch.

**Comment by methane** [comment]
Current setup.py https://github.com/farcepest/MySQLdb1/blob/master/setup.py
doesn't have `distribute_setup` dependency.
It is removed via 0d1dd6fa89 .

So this PR is not replace distribute_setup with ez_setup, but just add dependency to ez_setup.
Do you hope this?

**Comment by saschpe** [comment]
Oh, I can certainly live with that. I just wondered why github didn't refresh the pull and mark it non-mergeable.

**Pull request closed without merging**
