### PR TITLE
If setuptools is importable, don't force use of 'distribute'.

### PR DESCRIPTION
**Pull request by tseaver**
Allows use of post-merge setuptools 0.7.

### CODE REVIEW

**Comment by emonty** [comment]
I like this better than mine.

**Comment by stanhu** [comment]
+1 to merge.  Installing distribute 0.7.3 causes ugly error messages with other pip installs because MySQL-python attempts to pull in distribute 0.6.28.

**Comment by motiteux** [comment]
+1 to merge. Whatever implementation, this is really important for production servers that need to be upgraded to new setuptools...

**Comment by canassa** [comment]
+1

**Comment by s7v7nislands** [comment]
+1 
In 2013, the fork of Distribute was merged back into Setuptools

http://pythonhosted.org/setuptools/merge.html

**Pull request merged**
